name: all_in_music
description: "All In Music Streaming App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.3
  http: ^1.2.2
  just_audio: ^0.9.37
  provider: ^6.1.2
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
  fonts:
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/centurygothic.ttf
          weight: 400
        - asset: assets/fonts/centurygothic_bold.ttf
          weight: 700
